CREATE TABLE LOCATION (
  LOCATION_ID character varying(32) PRIMARY KEY,
  COUNTRY_ID character varying(32) NOT NULL REFERENCES COUNTRY(COUNTRY_ID),
  REGION_ID character varying(32) NOT NULL REFERENCES REGION(REGION_ID),
  DISTRICT_ID character varying(32) REFERENCES DISTRICT(DISTRICT_ID),
  TOWN_ID character varying(32) REFERENCES TOWN(TOWN_ID),
  TOWN_AREA_ID character varying(32) REFERENCES TOWN_AREA(TOWN_AREA_ID)
) WITH (OIDS=FALSE);