CREATE TABLE AUTH_STATE (
  USER_ID character varying(32) NOT NULL PRIMARY KEY,
  AUTH_STATE numeric(5,1) DEFAULT NULL,
  EXPIRATION bigint DEFAULT NULL,
  IP_ADDRESS character varying(20) DEFAULT NULL,
  LAST_LOGIN timestamp DEFAULT NULL,
  TOKEN character varying(100) DEFAULT NULL
) WITH (OIDS=FALSE);